name: team_love_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  table_calendar: ^3.1.2
  uuid: ^4.3.3
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_messaging: ^16.0.0
  firebase_storage: ^13.0.0
  firebase_app_check: ^0.4.0
  path_provider: ^2.1.5
  share_plus: ^12.0.0
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/TL_icon.png"
  min_sdk_android: 23

# Native splash (system + window background)
flutter_native_splash:
  color: "#FFFFFF"
  android: true
  ios: true

  android_12:
    color: "#FFFFFF"
    image: assets/icon/TL_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon/TL_icon.png
