// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHhtRz6hTqtCBhXkDr7nBv793tY4h961E',
    appId: '1:576026676741:android:0e9ade98551ace77f2966c',
    messagingSenderId: '576026676741',
    projectId: 'team-love-9c9b8',
    storageBucket: 'team-love-9c9b8.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfXoQuWDRDS3pXp5_V-WSc43twHtMOdeI',
    appId: '1:576026676741:web:a7aedaf437ac1b72f2966c',
    messagingSenderId: '576026676741',
    projectId: 'team-love-9c9b8',
    authDomain: 'team-love-9c9b8.firebaseapp.com',
    storageBucket: 'team-love-9c9b8.firebasestorage.app',
    measurementId: 'G-2RT4G6MKY6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7pOcrRSKL_G6MgDd3xH8mIUHWOByTAeY',
    appId: '1:576026676741:ios:e66920fd50c09e5bf2966c',
    messagingSenderId: '576026676741',
    projectId: 'team-love-9c9b8',
    storageBucket: 'team-love-9c9b8.firebasestorage.app',
    iosBundleId: 'com.example.teamLoveApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7pOcrRSKL_G6MgDd3xH8mIUHWOByTAeY',
    appId: '1:576026676741:ios:e66920fd50c09e5bf2966c',
    messagingSenderId: '576026676741',
    projectId: 'team-love-9c9b8',
    storageBucket: 'team-love-9c9b8.firebasestorage.app',
    iosBundleId: 'com.example.teamLoveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfXoQuWDRDS3pXp5_V-WSc43twHtMOdeI',
    appId: '1:576026676741:web:2a30e7f287ed234ef2966c',
    messagingSenderId: '576026676741',
    projectId: 'team-love-9c9b8',
    authDomain: 'team-love-9c9b8.firebaseapp.com',
    storageBucket: 'team-love-9c9b8.firebasestorage.app',
    measurementId: 'G-Z2XPJSL05M',
  );

}